In [1]:
import torch
from torch_geometric.data import Data

In [7]:
edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index.t().contiguous())

In [9]:
data.keys

['x', 'edge_index']

In [10]:
data['x']

tensor([[-1.],
        [ 0.],
        [ 1.]])

In [11]:
data.num_nodes

3

In [12]:
data.num_node_features

1

In [14]:
data.is_directed()

False

In [15]:
data.to

<bound method Data.to of Data(edge_index=[2, 4], x=[3, 1])>

In [16]:
from torch_geometric.datasets import TUDataset

dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES')

Extracting /tmp/ENZYMES/ENZYMES.zip
Processing...
Done!


In [21]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='/tmp/Cora', name='Cora')

Processing...
Done!


In [27]:
data = dataset[0]

In [28]:
data.train_mask

tensor([ True,  True,  True,  ..., False, False, False])

In [29]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='/tmp/Cora', name='Cora')

In [36]:
dataset[0].keys

['x', 'edge_index', 'y', 'train_mask', 'val_mask', 'test_mask']

In [47]:
dataset[0]['x'].shape

torch.Size([2708, 1433])

In [39]:
dataset[0]['edge_index']

tensor([[   0,    0,    0,  ..., 2707, 2707, 2707],
        [ 633, 1862, 2582,  ...,  598, 1473, 2706]])

In [41]:
dataset[0]['y'].shape

torch.Size([2708])

In [42]:
dataset[0]['train_mask'].shape

torch.Size([2708])

In [48]:
from torch_geometric.datasets import Entities
dataset = Entities('/tmp/MUTAG', 'MUTAG')

Extracting /tmp/MUTAG/mutag.tgz
Processing...
Done!


In [49]:
data = dataset[0]

In [52]:
edge_type = data.edge_type

In [55]:
edge_type.shape

torch.Size([148454])

In [56]:
data.edge_index

tensor([[    0,     0,     1,  ..., 23642, 23643, 23643],
        [ 5346, 21995,   872,  ..., 23389,  5352, 16256]])

In [58]:
data.